### PR TITLE
Fix my.harvard term querying

### LINKED ISSUE #8: Queries restricted to specific terms return more courses from my.harvard than expected
In order to get all courses offered in an academic year, we query the fall and spring term. However, we currently encode the term specification using the incorrect key, `Term`, instead of `STRM`.

Our mistake is using the "localized" name rather than the "unlocalized" one. For example, each course has a `Course Level` that indicates for which group of students a course is intended, and this localized name is displayed in my.harvard's search input for readability. However, the key actually sent in the HTTP request is the unlocalized name, `CRSE_ATTR_VALUE_HU_LEVL_ATTR`.

my.harvard's frontend supports either version of the key, transparently translating from localized to unlocalized. We do not do this, and **the REST API only supports unlocalized keys;** unrecognized search components are silently ignored. For example, the query, `anime (Course Level:"PRIMUGRD") (STRM:"2238" | Term:"2242")`, is the same as just `anime (STRM:"2238")`.

### PR DESCRIPTION
**Pull request by ColeFrench**
Fixes #8 and addresses #9.

Nothing crazy, except we are adding a new dependency on a very small library. The library provides a _limited writer_ that lets us store the first `n=1024` bytes of a response as plaintext while continuing to read the whole thing into a JSON decoder. If the decoding fails, then we print our little plaintext so the user can see what went wrong. We only store the first `n` bytes in case the response is very large.

### CODE REVIEW

File: datasource/myharvard.go [hunk 1]
```diff
@@ -40,9 +43,17 @@ func mhSearchRaw(search map[string]any) ([]any, error) {
 		return nil, fmt.Errorf("post request had bad status code: %v", resp.Status)
 	}
 
+	// Store the beginning of the response body into a buffer, so we can log it
+	// if there's an error.
+	var msgBuilder strings.Builder
+	msgBuilder.Grow(1024)
+	msgWriter := limitio.NewWriter(&msgBuilder, msgBuilder.Cap(), true)
```
Comment (ekzhang) [inline datasource/myharvard.go]: This is correct but probably too complicated, just use `io.ReadAll()` into a string and `json.Unmarshal()` instead of the combined `json.NewDecoder().decode()` function.

The decoder reads the entire string into memory first anyway for efficiency reasons.

**Review by ekzhang — APPROVED** [review]
Great work! Minor comment but it doesn't really matter

File: datasource/myharvard.go (hunk 1 above)
Comment (ColeFrench) [reply datasource/myharvard.go]: Ok! It feels more natural to me to use a decoder on a stream of data, and the current way will remain safe if the internals of the decoder change and my.harvard decides to drop a 1 GB HTML file on us (however unlikely).

Still, this is just a manual script, doing it the simpler way does make the code cleaner and more maintainable. I'll change it! We can always go back.

Comment (ekzhang) [reply datasource/myharvard.go]: It's fine if you want to do it this way, too! I don't want to nitpick, feel free to use limitio, not the most critical piece of code. Just wanted to make sure we're informed, [the JSON decoder internals won't change](https://github.com/golang/go/issues/11046#issuecomment-209646316)

Comment (ColeFrench) [reply datasource/myharvard.go]: Cool, thanks for the link!
